name: Claude Code Assistant

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, reopened, synchronize, edited]
  pull_request_review_comment:
    types: [created, edited]
  workflow_dispatch: {}

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write   # <-- required for the action to set up the GitHub token

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}  # <-- underscores
          github_token: ${{ github.token }}                    # <-- pass default token
